# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- master
- azure-pipelines

jobs:
- job: 32_bit
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm set npm_config_arch ia32
      npm install --arch=ia32 electron-prebuilt -g
      npm install --arch=ia32 electron-builder -g
      npm install --arch=ia32 electron-rebuild -g
      npm install --arch=ia32
      electron-rebuild -f --arch=ia32
      electron-builder --win --arch=ia32
    displayName: 'npm install and build 32-bit'
  
- job: 64_bit
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm install electron-builder -g
      npm run build
      electron-builder --win
    displayName: 'npm install and build 64-bit'